### ISSUE TITLE
Violation of License / Lizenzverletzung

### ISSUE THREAD

**Issue by miketotman-sd** [ecsec/2FA.jetzt#13]
Your fork is violating the [license](https://github.com/2factorauth/twofactorauth/blob/master/LICENSE) of the original by not including the copyright information or crediting the original on your website.

(Google Translation): Ihre Gabel verstößt gegen die Lizenz des Originals, indem sie die Urheberrechtsinformationen nicht einbezieht oder das Original auf Ihrer Website angibt.

**Comment by ecmrauh** [comment]
Thanks for reporting this issue. We changed our license file and made an additional hint in the [imprint](https://www.2fa.jetzt/Imprint.html) of the website.

**Comment by jamcat22** [comment]
@ecmrauh thanks for changing the license file. On the website, please change the imprint to include a notice that the sections based on the fork are licensed under the MIT license. You may also link to the license of this repo for further clarification. The current text of the imprint suggests that while those pages are based on the fork of twofactorauth.org, they're still covered under the overall CC-BY-SA 3.0 license of the website. Changing the text to explicitly mention the MIT license file will help remove any ambiguity.

**Comment by ecmrauh** [comment]
Thanks for your comment, @jamcat22. The website now mentions explicitly the MIT license of the three pages.
